const { contextBridge, ipcRenderer } = require("electron");

function subscription(channel, listener) {
  const wrapped = (_event, value) => listener(value);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld("codexWebLauncher", {
  snapshot: () => ipcRenderer.invoke("launcher:snapshot"),
  setLanguage: (language) => ipcRenderer.invoke("launcher:set-language", language),
  connectionStatus: () => ipcRenderer.invoke("launcher:connection-status"),
  reviewWebAccess: () => ipcRenderer.invoke("launcher:browser-access-review"),
  resumeWebAccess: () => ipcRenderer.invoke("launcher:browser-access-resume"),
  copyNativeCodexCommand: () => ipcRenderer.invoke("launcher:copy-native-command"),
  signInBrowsers: () => ipcRenderer.invoke("launcher:signin-browsers"),
  beginBrowserSignIn: browser => ipcRenderer.invoke("launcher:signin-begin", browser),
  browserSignInStatus: () => ipcRenderer.invoke("launcher:signin-status"),
  cancelBrowserSignIn: () => ipcRenderer.invoke("launcher:signin-cancel"),
  openSignInBrowser: (browser, action) => ipcRenderer.invoke("launcher:signin-open", browser, action),
  copyBrowserConnectionCode: () => ipcRenderer.invoke("launcher:signin-copy-code"),
  showBrowserConnector: () => ipcRenderer.invoke("launcher:signin-connector-files"),
  enableSafariConnector: () => ipcRenderer.invoke("launcher:signin-safari"),
  completeOnboarding: (language, browserInteractionMode) => ipcRenderer.invoke(
    "launcher:complete-onboarding",
    language,
    browserInteractionMode,
  ),
  openExternal: (url) => ipcRenderer.invoke("launcher:open-external", url),
  setBrowserBounds: (bounds) => ipcRenderer.invoke("launcher:browser-bounds", bounds),
  setBrowserSurfaceActive: (active) => ipcRenderer.invoke("launcher:browser-surface-active", active),
  showBrowser: () => ipcRenderer.invoke("launcher:browser-show"),
  hideBrowser: () => ipcRenderer.invoke("launcher:browser-hide"),
  navigateBrowser: (action) => ipcRenderer.invoke("launcher:browser-navigate", action),
  zoomBrowser: (action) => ipcRenderer.invoke("launcher:browser-zoom", action),
  selectBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-select", tabId),
  closeBrowserTab: (tabId) => ipcRenderer.invoke("launcher:browser-tab-close", tabId),
  copyManualPrompt: (tabId) => ipcRenderer.invoke("launcher:manual-prompt-copy", tabId),
  confirmManualSent: (tabId) => ipcRenderer.invoke("launcher:manual-prompt-sent", tabId),
  openLogin: () => ipcRenderer.invoke("launcher:browser-login"),
  openPasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login"),
  continuePasskeyLogin: () => ipcRenderer.invoke("launcher:browser-passkey-login-continue"),
  logoutChatGpt: () => ipcRenderer.invoke("launcher:browser-logout"),
  dismissSessionReminder: () => ipcRenderer.invoke("launcher:session-reminder-dismiss"),
  verifyMcp: () => ipcRenderer.invoke("launcher:mcp-verify"),
  doctor: () => ipcRenderer.invoke("launcher:doctor"),
  cancelTurns: () => ipcRenderer.invoke("launcher:cancel-turns"),
  uninstallIntegration: () => ipcRenderer.invoke("launcher:uninstall-integration"),
  setupCore: () => ipcRenderer.invoke("launcher:setup-core"),
  setupMcp: (input) => ipcRenderer.invoke("launcher:setup-mcp", input),
  setMcpStep: (step) => ipcRenderer.invoke("launcher:set-mcp-step", step),
  setAutostart: (enabled) => ipcRenderer.invoke("launcher:autostart", enabled),
  setBiggerContext: (enabled) => ipcRenderer.invoke("launcher:bigger-context", enabled),
  setZeroRiskPro: (enabled) => ipcRenderer.invoke("launcher:zero-risk-pro", enabled),
  setBrowserInteractionMode: (mode) => ipcRenderer.invoke("launcher:browser-interaction-mode", mode),
  setPreference: (key, value) => ipcRenderer.invoke("launcher:set-preference", key, value),
  setSidebarState: (state) => ipcRenderer.invoke("launcher:sidebar-state", state),
  logs: (limit) => ipcRenderer.invoke("launcher:logs", limit),
  exportLogs: () => ipcRenderer.invoke("launcher:export-logs"),
  installUpdate: () => ipcRenderer.invoke("launcher:update-install"),
  checkUpdates: () => ipcRenderer.invoke("launcher:update-check"),
  setUpdateToken: (token) => ipcRenderer.invoke("launcher:update-token", token),
  openReleases: () => ipcRenderer.invoke("launcher:update-releases"),
  windowState: () => ipcRenderer.invoke("launcher:window-state"),
  windowControl: (action) => ipcRenderer.send("launcher:window-control", action),
  onWindowStateChanged: (listener) => subscription("launcher:window-state-changed", listener),
  onStateChanged: (listener) => subscription("launcher:state-changed", listener),
  onBrowserState: (listener) => subscription("launcher:browser-state", listener),
  onOperation: (listener) => subscription("launcher:operation", listener),
  onLog: (listener) => subscription("launcher:log", listener),
  onUpdateState: (listener) => subscription("launcher:update-state", listener),
});
