import type { Language } from "./types";

const en = {
  welcome: "Your work. Less setup.", welcomeBody: "Connect ChatGPT to Codex in one guided flow. Maria handles the installation, remembers your settings, and checks that the connection is working.",
  welcomeAction: "Connect my workspace", welcomeNote: "You stay in control of sign-in and permissions. No terminal commands needed for launcher setup.",
  recommended: "Recommended", advanced: "Advanced controls", advancedBody: "Your models, tool connection, and technical settings are always available here.",
  home: "Overview", connection: "Connection", chat: "ChatGPT", activity: "Activity", settings: "Settings", help: "Help & guides", updates: "Updates", find: "Find anything",
  automatic: "Let Maria handle setup", manual: "Manual interaction", choiceHint: "Automation is recommended. Manual mode keeps sending and browser interaction in your hands.",
  setup: "Connect your workspace", setupBody: "A few checks. One clear next step. Maria takes care of the technical work.",
  start: "Set up my workspace", check: "Check connection", continue: "Continue setup", pause: "Pause", paused: "Setup is paused", pausedBody: "Any installation already started finishes safely. Continue whenever you are ready.",
  checking: "Checking your workspace", checkingBody: "Looking for your saved account, settings, and connection. Nothing needs to be entered again when it is already available.",
  busy: "Your current work comes first", busyBody: "Maria will continue after the active task or operation finishes. Your work will not be interrupted.",
  signIn: "Sign in once", signInBody: "Complete your ChatGPT sign-in in the browser. Maria will detect it and continue setup automatically.",
  review: "A confirmation needs you", reviewBody: "Complete the verification or access review in ChatGPT. Maria will not dismiss it or bypass a cooldown.",
  credentials: "Connect your tools", credentialsBody: "Add your workspace's tunnel and restricted key once. Maria handles installation and reuses the saved connection next time.",
  installing: "Maria is setting things up", installingBody: "Installing the integration and checking the runtime. You do not need to copy commands or edit configuration files.",
  codex: "One last step in Codex", codexBody: "Finish any active work, fully quit and reopen Codex, then open its model picker. Maria detects the refreshed catalog automatically.",
  connector: "Approve the tool connection", connectorBody: "Connect the named app in your ChatGPT workspace, then continue. Maria checks the connection before marking it ready.",
  verifying: "Making sure everything connects", verifyingBody: "Checking the installed runtime and the connections required by your chosen setup.",
  ready: "You're ready to work", readyBody: "The setup checks passed. Open Codex, choose a ChatGPT Web model, and get back to your work.",
  openChat: "Open ChatGPT", openSignIn: "Open sign-in", openTools: "Connect tools", openReview: "Review connection", reopened: "I've reopened Codex", reviewDetails: "Review details", details: "Technical details", backHome: "Back to overview",
  stepAccount: "ChatGPT account", stepRuntime: "Install integration", stepCodex: "Codex models", stepTools: "Local tools", stepCheck: "Connection checks", done: "Complete", current: "Current step", upcoming: "Not yet checked", optional: "Optional", automaticStep: "Handled by Maria", yourStep: "Needs your confirmation",
  target: "What would you like to connect?", basic: "ChatGPT in Codex", basicBody: "Use your available Web models. No tool credentials needed.", full: "ChatGPT + local tools", fullBody: "Add access to your Codex tools through your own connector.", saved: "Using your saved connection", preserved: "Existing settings are reused. Account permissions remain yours to approve.", progress: "Setup progress", stepsComplete: "steps complete",
  workTitle: "Your workspace", workBody: "Your active and retained conversations, in one place.", empty: "Room for your next idea", emptyBody: "Start a task in Codex with a ChatGPT Web model. Its conversation will appear here.", noWorkYet: "Finish the connection above to get started.", task: "Conversation", running: "Working", retained: "Retained", attention: "Needs attention", connected: "Connected", unknown: "Checking", offline: "Not connected", recovering: "Reconnecting", resume: "Open conversation", liveStatus: "Connection status", native: "Codex connection", account: "ChatGPT session", tools: "Tool connection", notEnabled: "Not enabled", manualSession: "Managed by you", privacy: "Your settings stay on this computer", optionalTools: "Add local tools", optionalToolsBody: "Connect your own tool credentials when you need more than chat.",
  helpTitle: "A little help, right here", helpBody: "Most setup is automatic. These are the parts that may need you.", helpSetup: "Continue guided setup", helpActivity: "Check connection activity", handbook: "Technical handbook", helpQuestions: [
    ["What does Maria do for me?", "Maria checks saved settings, installs the integration, reuses available tool credentials, and verifies the connection. The setup card shows the exact step that is running."],
    ["Do I need an API key?", "ChatGPT-in-Codex setup does not require tool credentials. Connecting local tools requires your own tunnel and a restricted key with Tunnels Read and Use permissions. Maria does not create an account or grant permissions for you."],
    ["Why does setup ask me to reopen Codex?", "Codex needs to request the refreshed model catalog. Finish your active work, fully quit and reopen Codex, and open the model picker. Signing out or closing only the window is not a full restart."],
    ["What happens when a connection fails?", "Maria retries temporary local startup failures within a bounded budget. Sign-in, access checks, and failed recovery are shown explicitly. Your selected model is never silently replaced."],
  ],
  preferencesBody: "The essentials first. Advanced options stay out of your way until you need them.", diagnostics: "Troubleshooting & recovery", diagnosticsBody: "Inspect connection health, export a safe log, or remove the integration.",
};
type GuidedCopy = { [K in keyof typeof en]: typeof en[K] extends string ? string : string[][] };
const ja: GuidedCopy = {
  ...en,
  welcome: "作業をもっと、設定を少なく。", welcomeBody: "ChatGPT と Codex をひとつの流れで接続します。Maria がインストール、設定の再利用、接続確認を行います。", welcomeAction: "ワークスペースを接続", welcomeNote: "ログインと権限は自分で確認できます。ランチャーの設定にターミナル操作は不要です。",
  recommended: "推奨", advanced: "詳細設定", advancedBody: "モデル、ツール接続、技術的な設定はこちら。", home: "概要", connection: "接続", chat: "ChatGPT", activity: "アクティビティ", settings: "設定", help: "ヘルプ", updates: "アップデート", find: "機能を検索", automatic: "設定を Maria に任せる", manual: "手動操作", choiceHint: "自動操作を推奨します。手動モードでは送信とブラウザー操作を自分で行います。",
  setup: "ワークスペースを接続", setupBody: "必要な確認を順番に。技術的な作業は Maria が行います。", start: "自動セットアップ", check: "接続を確認", continue: "設定を続ける", pause: "一時停止", paused: "設定を一時停止中", pausedBody: "開始済みのインストールは安全に完了します。準備ができたら続行してください。", checking: "ワークスペースを確認中", checkingBody: "保存済みアカウント、設定、接続を確認しています。利用できる情報の再入力は不要です。", busy: "現在の作業を優先します", busyBody: "タスクや処理の終了後に自動で続行します。作業は中断しません。", signIn: "ChatGPT にログイン", signInBody: "ブラウザーでログインを完了してください。確認でき次第、自動で続行します。", review: "確認が必要です", reviewBody: "ChatGPT の認証やアクセス確認を完了してください。待機制限は回避しません。", credentials: "ツールを接続", credentialsBody: "ワークスペースのトンネルと制限付きキーを一度登録すると、次回から保存済み接続を再利用します。", installing: "Maria が設定中", installingBody: "統合のインストールとランタイム確認を行っています。コマンドや設定ファイルの編集は不要です。", codex: "Codex で最後の確認", codexBody: "作業を保存して Codex を完全に終了し、開き直してモデル選択を開いてください。更新を自動で検出します。", connector: "ツール接続を承認", connectorBody: "ChatGPT のワークスペースで指定のアプリを接続して続行してください。Maria が接続を検証します。", verifying: "接続を検証中", verifyingBody: "選択した設定に必要なランタイムと接続を確認しています。", ready: "作業の準備ができました", readyBody: "設定確認が完了しました。Codex で ChatGPT Web モデルを選んで作業を始めてください。",
  openChat: "ChatGPT を開く", openSignIn: "ログインを開く", openTools: "ツールを接続", openReview: "接続を確認", reopened: "Codex を開き直しました", reviewDetails: "詳細を確認", details: "技術的な詳細", backHome: "概要に戻る", stepAccount: "ChatGPT アカウント", stepRuntime: "統合のインストール", stepCodex: "Codex モデル", stepTools: "ローカルツール", stepCheck: "接続確認", done: "完了", current: "現在のステップ", upcoming: "未確認", optional: "任意", automaticStep: "Maria が処理", yourStep: "確認が必要", target: "接続する機能", basic: "Codex で ChatGPT", basicBody: "利用可能な Web モデルを使用。ツール認証情報は不要です。", full: "ChatGPT とローカルツール", fullBody: "自分のコネクターで Codex ツールも利用。", saved: "保存済み接続を再利用", preserved: "既存の設定を再利用します。アカウント権限は自分で承認できます。", progress: "設定の進捗", stepsComplete: "ステップ完了", workTitle: "ワークスペース", workBody: "進行中・保持中の会話をひとつの場所に。", empty: "次のアイデアのために", emptyBody: "Codex の ChatGPT Web モデルでタスクを開始すると、ここに会話が表示されます。", noWorkYet: "上の接続設定を完了してください。", task: "会話", running: "処理中", retained: "保持中", attention: "確認が必要", connected: "接続済み", unknown: "確認中", offline: "未接続", recovering: "再接続中", resume: "会話を開く", liveStatus: "接続状態", native: "Codex 接続", account: "ChatGPT セッション", tools: "ツール接続", notEnabled: "未設定", manualSession: "手動で管理", privacy: "設定はこのコンピューターに保存", optionalTools: "ローカルツールを追加", optionalToolsBody: "ツールが必要になったら、自分の認証情報で接続できます。", helpTitle: "ここでお手伝いします", helpBody: "通常の設定は自動です。操作が必要な場面をご案内します。", helpSetup: "自動設定を続ける", helpActivity: "接続の履歴を確認", handbook: "技術マニュアル", helpQuestions: [
    ["Maria は何をしてくれますか？", "保存済み設定の確認、統合のインストール、利用可能な認証情報の再利用、接続の検証を行います。設定カードに現在の処理を表示します。"],
    ["API キーは必要ですか？", "Codex で ChatGPT を使う基本設定には不要です。ローカルツールには自分のトンネルと Tunnels Read・Use の制限付きキーが必要です。アカウント作成や権限付与は自動で行いません。"],
    ["なぜ Codex の再起動が必要ですか？", "更新されたモデル一覧を取得するためです。作業を終え、Codex を完全に終了して開き直し、モデル選択を開いてください。ログインし直すだけでは再起動になりません。"],
    ["接続に失敗したら？", "一時的なローカル起動エラーは回数と時間を制限して再試行します。ログイン、権限、復旧の問題は明示し、選択したモデルを勝手に変更しません。"],
  ], preferencesBody: "基本設定を先に。詳細設定は必要なときに開けます。", diagnostics: "診断と復旧", diagnosticsBody: "接続状態の確認、安全なログの出力、統合の削除。",
};
const zh: GuidedCopy = {
  ...en,
  welcome: "专注工作，少做设置。", welcomeBody: "在一个引导流程中连接 ChatGPT 和 Codex。Maria 负责安装、记住设置并检查连接。", welcomeAction: "连接我的工作区", welcomeNote: "登录与权限由你确认。启动器设置无需终端命令。", recommended: "推荐", advanced: "高级控制", advancedBody: "模型、工具连接和技术设置始终可以在这里找到。", home: "概览", connection: "连接", chat: "ChatGPT", activity: "活动", settings: "设置", help: "帮助与指南", updates: "更新", find: "查找功能", automatic: "让 Maria 完成设置", manual: "手动交互", choiceHint: "推荐使用自动化。手动模式由你负责发送和浏览器操作。", setup: "连接你的工作区", setupBody: "逐步检查，下一步清晰可见。技术工作交给 Maria。", start: "自动设置工作区", check: "检查连接", continue: "继续设置", pause: "暂停", paused: "设置已暂停", pausedBody: "已开始的安装会安全完成。准备好后可继续。", checking: "正在检查工作区", checkingBody: "查找已保存的账号、设置和连接。已有的信息无需重新输入。", busy: "优先完成当前工作", busyBody: "当前任务或操作结束后自动继续，不会打断你的工作。", signIn: "登录一次即可", signInBody: "在浏览器完成 ChatGPT 登录，Maria 检测后会自动继续。", review: "需要你的确认", reviewBody: "请完成 ChatGPT 的验证或访问确认。Maria 不会跳过验证或冷却时间。", credentials: "连接你的工具", credentialsBody: "添加工作区隧道和受限密钥一次，Maria 负责安装并在下次复用。", installing: "Maria 正在完成设置", installingBody: "正在安装集成并检查运行时，无需复制命令或编辑配置文件。", codex: "在 Codex 完成最后一步", codexBody: "完成当前工作，完全退出并重新打开 Codex，然后打开模型选择器。Maria 会自动检测更新的目录。", connector: "批准工具连接", connectorBody: "在 ChatGPT 工作区连接指定应用后继续。Maria 会先验证连接再标记就绪。", verifying: "正在验证连接", verifyingBody: "检查所选设置需要的运行时与连接。", ready: "可以开始工作了", readyBody: "设置检查已通过。打开 Codex，选择 ChatGPT Web 模型，开始工作。", openChat: "打开 ChatGPT", openSignIn: "打开登录", openTools: "连接工具", openReview: "检查连接", reopened: "我已重新打开 Codex", reviewDetails: "查看详情", details: "技术详情", backHome: "返回概览", stepAccount: "ChatGPT 账号", stepRuntime: "安装集成", stepCodex: "Codex 模型", stepTools: "本地工具", stepCheck: "连接检查", done: "已完成", current: "当前步骤", upcoming: "尚未检查", optional: "可选", automaticStep: "由 Maria 处理", yourStep: "需要你确认", target: "你想连接什么？", basic: "在 Codex 使用 ChatGPT", basicBody: "使用可用的 Web 模型，无需工具凭据。", full: "ChatGPT 与本地工具", fullBody: "通过自己的连接器添加 Codex 工具访问。", saved: "正在复用已保存的连接", preserved: "复用现有设置，账号权限仍由你批准。", progress: "设置进度", stepsComplete: "步已完成", workTitle: "你的工作区", workBody: "在一处查看运行中和保留的对话。", empty: "为下一个灵感留出空间", emptyBody: "在 Codex 使用 ChatGPT Web 模型开始任务，对话会显示在这里。", noWorkYet: "先完成上方连接设置即可开始。", task: "对话", running: "运行中", retained: "已保留", attention: "需要处理", connected: "已连接", unknown: "检查中", offline: "未连接", recovering: "正在重连", resume: "打开对话", liveStatus: "连接状态", native: "Codex 连接", account: "ChatGPT 会话", tools: "工具连接", notEnabled: "未启用", manualSession: "由你管理", privacy: "设置保留在此计算机", optionalTools: "添加本地工具", optionalToolsBody: "需要聊天以外的功能时，可连接自己的工具凭据。", helpTitle: "帮助就在这里", helpBody: "大多数设置自动完成。下面是可能需要你操作的部分。", helpSetup: "继续引导设置", helpActivity: "查看连接活动", handbook: "技术手册", helpQuestions: [
    ["Maria 会帮我做什么？", "检查保存的设置、安装集成、复用可用的工具凭据并验证连接。设置卡片会显示正在运行的确切步骤。"],
    ["需要 API 密钥吗？", "在 Codex 中使用 ChatGPT 的基本设置不需要工具凭据。本地工具需要自己的隧道和具有 Tunnels Read、Use 权限的受限密钥。Maria 不会替你创建账号或授权。"],
    ["为什么需要重新打开 Codex？", "Codex 需要获取更新的模型目录。完成工作后完全退出并重新打开，再打开模型选择器。仅重新登录或关闭窗口不算完整重启。"],
    ["连接失败怎么办？", "Maria 会在限定范围内重试暂时的本地启动故障。登录、访问检查和恢复失败会明确显示，绝不会悄悄替换所选模型。"],
  ], preferencesBody: "先显示基本设置，需要时再展开高级选项。", diagnostics: "诊断与恢复", diagnosticsBody: "检查连接、导出安全日志或移除集成。",
};
export function guidedCopy(language: Language | null | undefined): GuidedCopy {
  return language === "ja" ? ja : language === "zh-CN" ? zh : en;
}
