import type { Language } from "./types";

const en = {
  accountStepBody: "Sign in to the ChatGPT account you want to use.", modelStepBody: "Add ChatGPT Web models to the Codex model picker.", toolsStepBody: "Connect tools so ChatGPT can work with your Codex task.",
  continueTask: "Continue task", reviewBrowser: "Review ChatGPT", connectTools: "Connect tools",
  connectionDetails: "Connection details", refreshStatus: "Refresh connection status", nextStep: "Up next", setupComplete: "Setup complete",
  openingGuide: "Opening the guide…", guideUnavailable: "The guide could not be loaded.", guideOnline: "Open guide on GitHub",
  workspace: "Your workspace", greeting: "A good place to keep building.",
  intro: "Your models, conversations, and tools. Together in Maria.",
  connections: "Connections", conversations: "Conversations", openWorkspace: "Open workspace",
  emptyTitle: "Your next idea starts here.", emptyBody: "Choose a ChatGPT Web model in Codex to begin. Your conversations will appear here as you work.",
  emptyAction: "Open ChatGPT", manageModels: "Manage models", finishSetup: "Finish connection setup",
  native: "Native Codex", web: "ChatGPT account", tools: "Workspace tools",
  connected: "Connected", ready: "Ready", checking: "Checking", attention: "Needs attention",
  signIn: "Sign in", connect: "Connect", working: "Working", retained: "Saved session",
  mode: "Working mode", automatic: "Automatic", manual: "Manual", edit: "Change",
  setup: "Connection setup", setupHint: "Pick up where you left off.",
  modelTitle: "Two ways to work. One workspace.",
  nativeBody: "Your regular Codex models and tools, using your Codex account.",
  webBody: "ChatGPT models with access to the tools in your current Codex task.",
  learn: "How it works", guide: "A little guidance, when you need it.",
  guideBody: "Connect your account, choose a model, and keep your work moving.",
  guideAction: "Read the guide", copyNative: "Copy native launch command", copied: "Command copied",
  command: "Jump to a page", search: "Search pages…", noResults: "No matching pages.",
  keyboardHint: "Navigate", selectHint: "Open", closeHint: "Close",
  all: "All activity", errors: "Errors", warnings: "Warnings", searchActivity: "Search activity…",
  matching: "events", noMatches: "No activity matches your search.", pause: "Pause view", resume: "Resume live view",
  welcomeTitle: "Make room for your best work.", welcomeBody: "Connect ChatGPT to your coding workspace with a quieter, more considered way to work.",
  preferences: "A few preferences", preferencesBody: "Choose your language and how you want to work. You can change both in Settings.",
  language: "Language", behavior: "How Maria works", getStarted: "Get started",
  setupProgress: "complete", modelReady: "Your models are connected.", modelPending: "Two steps. Then you are ready to work.",
  setupPrivacy: "Setup checks your account's available models. It does not send a ChatGPT message.",
  nativeAvailable: "Native Codex stays available through your regular account.",
  workflow: "ChatGPT workflow", startup: "Startup & background", experience: "Your preferences",
  diagnostics: "Connection & recovery", version: "Version",
};

const zh: typeof en = {
  accountStepBody: "登录你想使用的 ChatGPT 账户。", modelStepBody: "将 ChatGPT Web 模型添加到 Codex 模型选择器。", toolsStepBody: "连接工具，让 ChatGPT 处理你的 Codex 任务。",
  continueTask: "继续任务", reviewBrowser: "查看 ChatGPT", connectTools: "连接工具",
  connectionDetails: "连接详情", refreshStatus: "刷新连接状态", nextStep: "下一步", setupComplete: "设置完成",
  openingGuide: "正在打开指南…", guideUnavailable: "无法加载指南。", guideOnline: "在 GitHub 上打开指南",
  workspace: "你的工作空间", greeting: "继续创造的好地方。", intro: "模型、对话与工具，都在 Maria。",
  connections: "连接", conversations: "对话", openWorkspace: "打开工作空间",
  emptyTitle: "下一个想法，从这里开始。", emptyBody: "在 Codex 中选择 ChatGPT Web 模型开始工作。对话会显示在这里。",
  emptyAction: "打开 ChatGPT", manageModels: "管理模型", finishSetup: "完成连接设置",
  native: "原生 Codex", web: "ChatGPT 账户", tools: "工作空间工具",
  connected: "已连接", ready: "就绪", checking: "检查中", attention: "需要处理", signIn: "登录", connect: "连接", working: "运行中", retained: "已保存的会话",
  mode: "工作模式", automatic: "自动", manual: "手动", edit: "更改", setup: "连接设置", setupHint: "从上次的进度继续。",
  modelTitle: "两种方式，同一工作空间。", nativeBody: "使用 Codex 账户访问常规模型和工具。", webBody: "让 ChatGPT 模型使用当前 Codex 任务中的工具。",
  learn: "了解详情", guide: "在需要时，提供一点指引。", guideBody: "连接账户，选择模型，然后继续工作。", guideAction: "阅读指南",
  copyNative: "复制原生启动命令", copied: "命令已复制", command: "跳转到页面", search: "搜索页面…", noResults: "没有匹配的页面。",
  keyboardHint: "导航", selectHint: "打开", closeHint: "关闭", all: "全部活动", errors: "错误", warnings: "警告", searchActivity: "搜索活动…",
  matching: "条事件", noMatches: "没有匹配的活动。", pause: "暂停显示", resume: "恢复实时显示",
  welcomeTitle: "为出色的工作留出空间。", welcomeBody: "将 ChatGPT 连接到你的编程工作空间，以更专注的方式工作。",
  preferences: "设置偏好", preferencesBody: "选择语言和工作方式。之后可在设置中更改。", language: "语言", behavior: "Maria 的工作方式", getStarted: "开始使用",
  setupProgress: "完成", modelReady: "模型已连接。", modelPending: "两步即可开始工作。",
  setupPrivacy: "设置仅检查账户可用模型，不会发送 ChatGPT 消息。", nativeAvailable: "常规账户的原生 Codex 仍可使用。",
  workflow: "ChatGPT 工作流程", startup: "启动与后台", experience: "个人偏好", diagnostics: "连接与恢复", version: "版本",
};

const ja: typeof en = {
  accountStepBody: "使用する ChatGPT アカウントにサインインします。", modelStepBody: "Codex のモデル選択に ChatGPT Web モデルを追加します。", toolsStepBody: "ツールを接続して、ChatGPT が Codex の作業を進められるようにします。",
  continueTask: "作業を続ける", reviewBrowser: "ChatGPT を確認", connectTools: "ツールを接続",
  connectionDetails: "接続の詳細", refreshStatus: "接続状態を更新", nextStep: "次のステップ", setupComplete: "設定完了",
  openingGuide: "ガイドを開いています…", guideUnavailable: "ガイドを読み込めませんでした。", guideOnline: "GitHub でガイドを開く",
  workspace: "ワークスペース", greeting: "次の仕事を、ここから。", intro: "モデル、会話、ツールを Maria に。",
  connections: "接続", conversations: "会話", openWorkspace: "ワークスペースを開く",
  emptyTitle: "次のアイデアは、ここから。", emptyBody: "Codex で ChatGPT Web モデルを選んで始めましょう。作業中の会話がここに表示されます。",
  emptyAction: "ChatGPT を開く", manageModels: "モデルを管理", finishSetup: "接続設定を完了",
  native: "ネイティブ Codex", web: "ChatGPT アカウント", tools: "ワークスペースのツール",
  connected: "接続済み", ready: "準備完了", checking: "確認中", attention: "確認が必要", signIn: "サインイン", connect: "接続", working: "実行中", retained: "保存済みセッション",
  mode: "動作モード", automatic: "自動", manual: "手動", edit: "変更", setup: "接続設定", setupHint: "前回の続きから始めましょう。",
  modelTitle: "二つの方法。一つのワークスペース。", nativeBody: "Codex アカウントで通常のモデルとツールを利用できます。", webBody: "ChatGPT モデルが現在の Codex タスクのツールを利用します。",
  learn: "仕組みを見る", guide: "必要なときに、少しのガイドを。", guideBody: "アカウントを接続し、モデルを選んで作業を続けましょう。", guideAction: "ガイドを読む",
  copyNative: "起動コマンドをコピー", copied: "コピーしました", command: "ページに移動", search: "ページを検索…", noResults: "一致するページはありません。",
  keyboardHint: "移動", selectHint: "開く", closeHint: "閉じる", all: "すべて", errors: "エラー", warnings: "警告", searchActivity: "アクティビティを検索…",
  matching: "件", noMatches: "一致するアクティビティはありません。", pause: "表示を一時停止", resume: "リアルタイム表示を再開",
  welcomeTitle: "いい仕事のための余白を。", welcomeBody: "ChatGPT とコーディング環境をつなぎ、落ち着いて作業できる場所をつくります。",
  preferences: "初期設定", preferencesBody: "言語と動作モードを選びます。設定からいつでも変更できます。", language: "言語", behavior: "Maria の動作", getStarted: "はじめる",
  setupProgress: "完了", modelReady: "モデルは接続済みです。", modelPending: "二つのステップで準備完了。",
  setupPrivacy: "設定では利用可能なモデルを確認するだけで、ChatGPT にメッセージは送信しません。", nativeAvailable: "通常のアカウントでネイティブ Codex を引き続き利用できます。",
  workflow: "ChatGPT のワークフロー", startup: "起動とバックグラウンド", experience: "環境設定", diagnostics: "接続と復旧", version: "バージョン",
};

export const studioCopy = (language: Language | null) => language === "zh-CN" ? zh : language === "ja" ? ja : en;
