import type { Language } from "./types";
const en = {
  title: "Updates", body: "Maria checks for new releases. Install when your work is finished; your saved settings stay in place.",
  status: { disabled: "Your development workspace", idle: "Check for a new release", checking: "Checking published releases", "up-to-date": "You're up to date", ahead: "You're using a newer build", available: "An update is ready", downloading: "Downloading the update", installing: "Installing Maria", error: "The update check needs another try", "access-required": "GitHub access is required" },
  releaseStatus: "Release status", installed: "Installed on this computer", preview: "Preview build", stable: "Release channel", candidate: "Available version", latest: "Latest published release", source: "Source and DEV installations stay isolated. Update your checkout to get the latest code.", verified: "Maria verifies the download before installing and reopening. Your saved configuration and ChatGPT session are preserved.", finish: "Finish the active task or operation before installing.", update: "Install update", downloading: "Downloading…", installing: "Installing…", check: "Check for updates", checking: "Checking…", notes: "Release notes & downloads", last: "Last successful check", none: "No successful release check yet", automatic: "Checks automatically every four hours.", access: "Private GitHub access", connected: "Connected", optional: "Optional", accessBody: "Public releases do not need a GitHub token. For private releases, use a fine-grained token limited to this repository with Contents: Read-only. Maria stores it encrypted using your operating system and sends it only to the repository's GitHub release API.", token: "GitHub access token", connect: "Connect & check", remove: "Remove saved access",
};
type Copy = Omit<{ [K in keyof typeof en]: string }, "status"> & { status: { [K in keyof typeof en.status]: string } };
const ja: Copy = { title: "アップデート", body: "Maria が新しいリリースを確認します。作業完了後にインストールできます。保存済み設定は保持されます。", status: { disabled: "開発ワークスペース", idle: "新しいリリースを確認", checking: "公開リリースを確認中", "up-to-date": "最新の状態です", ahead: "新しいビルドを使用中", available: "更新できます", downloading: "更新をダウンロード中", installing: "Maria をインストール中", error: "更新確認を再試行してください", "access-required": "GitHub アクセスが必要です" }, releaseStatus: "リリース状態", installed: "このコンピューターにインストール済み", preview: "プレビュービルド", stable: "リリースチャンネル", candidate: "利用可能なバージョン", latest: "最新の公開リリース", source: "ソースと DEV 環境は独立しています。コードを取得して更新してください。", verified: "Maria はダウンロードを検証してからインストール・再起動します。保存済み設定と ChatGPT セッションは保持されます。", finish: "実行中のタスクや処理を終えてからインストールしてください。", update: "更新をインストール", downloading: "ダウンロード中…", installing: "インストール中…", check: "更新を確認", checking: "確認中…", notes: "リリースノートとダウンロード", last: "最後に成功した確認", none: "まだ確認に成功していません", automatic: "4 時間ごとに自動確認します。", access: "非公開 GitHub アクセス", connected: "接続済み", optional: "任意", accessBody: "公開リリースにはトークンは不要です。非公開リリースには、このリポジトリのみの Contents: Read-only 権限を持つ細粒度トークンを使用してください。OS の機能で暗号化して保存し、リポジトリの GitHub リリース API のみに送信します。", token: "GitHub アクセストークン", connect: "接続して確認", remove: "保存済みアクセスを削除" };
const zh: Copy = { title: "更新", body: "Maria 会检查新版本。完成工作后再安装，已保存的设置会保留。", status: { disabled: "开发工作区", idle: "检查新版本", checking: "正在检查已发布版本", "up-to-date": "已是最新版本", ahead: "正在使用更新的构建", available: "更新已就绪", downloading: "正在下载更新", installing: "正在安装 Maria", error: "请重试更新检查", "access-required": "需要 GitHub 访问权限" }, releaseStatus: "版本状态", installed: "此计算机已安装", preview: "预览构建", stable: "发布通道", candidate: "可用版本", latest: "最新已发布版本", source: "源码与 DEV 安装保持隔离。请更新代码以获取最新版本。", verified: "Maria 先验证下载内容再安装并重新打开。保存的配置与 ChatGPT 会话会保留。", finish: "请完成当前任务或操作后再安装。", update: "安装更新", downloading: "正在下载…", installing: "正在安装…", check: "检查更新", checking: "正在检查…", notes: "版本说明与下载", last: "上次成功检查", none: "尚无成功的版本检查", automatic: "每四小时自动检查一次。", access: "私有 GitHub 访问", connected: "已连接", optional: "可选", accessBody: "公开版本不需要 GitHub 令牌。私有版本请使用仅限此仓库且具有 Contents: Read-only 权限的细粒度令牌。Maria 通过操作系统加密保存，仅将其发送到本仓库的 GitHub 发布 API。", token: "GitHub 访问令牌", connect: "连接并检查", remove: "删除保存的访问凭据" };
export function updatesCopy(language: Language | null): Copy { return language === "ja" ? ja : language === "zh-CN" ? zh : en; }
